"""Builds a digest summary aggregating multiple severity reports into one output."""

from dataclasses import dataclass, field
from typing import List, Optional

from depwatch.severity_report import SeverityReport
from depwatch.severity_classifier import Severity, highest_severity


@dataclass
class DigestSummary:
    reports: List[SeverityReport] = field(default_factory=list)
    total_packages: int = 0
    affected_packages: int = 0
    overall_severity: Severity = Severity.SAFE
    critical_packages: List[str] = field(default_factory=list)
    high_packages: List[str] = field(default_factory=list)


def build_digest(reports: List[SeverityReport]) -> DigestSummary:
    """Aggregate a list of SeverityReports into a DigestSummary."""
    if not reports:
        return DigestSummary()

    critical_packages: List[str] = []
    high_packages: List[str] = []
    all_severities: List[Severity] = []

    for report in reports:
        all_severities.append(report.highest_severity)
        if report.highest_severity == Severity.CRITICAL:
            critical_packages.append(report.package)
        elif report.highest_severity == Severity.HIGH:
            high_packages.append(report.package)

    affected = sum(1 for r in reports if r.highest_severity != Severity.SAFE)
    overall = highest_severity(all_severities)

    return DigestSummary(
        reports=reports,
        total_packages=len(reports),
        affected_packages=affected,
        overall_severity=overall,
        critical_packages=critical_packages,
        high_packages=high_packages,
    )


def format_digest_markdown(digest: DigestSummary) -> str:
    """Render a DigestSummary as a Markdown string."""
    lines: List[str] = []
    lines.append("## DepWatch Digest")
    lines.append("")
    lines.append(
        f"**Packages scanned:** {digest.total_packages}  "
        f"**Affected:** {digest.affected_packages}  "
        f"**Overall severity:** `{digest.overall_severity.value}`"
    )
    lines.append("")

    if digest.critical_packages:
        pkgs = ", ".join(f"`{p}`" for p in digest.critical_packages)
        lines.append(f"🔴 **Critical:** {pkgs}")
    if digest.high_packages:
        pkgs = ", ".join(f"`{p}`" for p in digest.high_packages)
        lines.append(f"🟠 **High:** {pkgs}")
    if not digest.critical_packages and not digest.high_packages:
        lines.append("✅ No critical or high severity changes detected.")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [depwatch](https://github.com/depwatch/depwatch)*")
    return "\n".join(lines)
