"""Formats depwatch analysis results for various output targets."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class PackageReport:
    package: str
    old_version: str
    new_version: str
    breaking_changes: List[str]
    summary: str


def format_table_row(report: PackageReport) -> str:
    """Format a single package report as a markdown table row."""
    status = "⚠️ Breaking" if report.breaking_changes else "✅ Safe"
    count = len(report.breaking_changes)
    return (
        f"| `{report.package}` "
        f"| `{report.old_version}` → `{report.new_version}` "
        f"| {status} "
        f"| {count} |"
    )


def format_markdown_report(reports: List[PackageReport]) -> str:
    """Render a full markdown report for all updated packages."""
    if not reports:
        return "## 🔍 DepWatch: No dependency changes detected.\n"

    lines: List[str] = [
        "## 🔍 DepWatch: Dependency Change Report",
        "",
        "| Package | Version | Status | Breaking Changes |",
        "|---------|---------|--------|------------------|",
    ]

    for report in reports:
        lines.append(format_table_row(report))

    breaking_reports = [r for r in reports if r.breaking_changes]
    if breaking_reports:
        lines.append("")
        lines.append("### ⚠️ Breaking Change Details")
        for report in breaking_reports:
            lines.append("")
            lines.append(f"#### `{report.package}` ({report.old_version} → {report.new_version})")
            lines.append("")
            lines.append(report.summary)

    lines.append("")
    lines.append("---")
    lines.append("_Generated by [DepWatch](https://github.com/depwatch/depwatch)_")
    return "\n".join(lines) + "\n"


def format_plain_text_report(reports: List[PackageReport]) -> str:
    """Render a plain-text summary suitable for CI logs."""
    if not reports:
        return "DepWatch: No dependency changes detected.\n"

    lines: List[str] = ["DepWatch Dependency Change Report", "=" * 36]
    for report in reports:
        flag = "[BREAKING]" if report.breaking_changes else "[OK]"
        lines.append(
            f"{flag} {report.package}: {report.old_version} -> {report.new_version}"
            f" ({len(report.breaking_changes)} breaking change(s))"
        )
        if report.breaking_changes:
            for change in report.breaking_changes:
                lines.append(f"  - {change}")
    return "\n".join(lines) + "\n"
