"""Builds and posts PR review comments via the GitHub API."""

import os
import requests

GITHUB_API_BASE = "https://api.github.com"


def get_github_token() -> str:
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        raise EnvironmentError("GITHUB_TOKEN environment variable is not set.")
    return token


def build_comment_body(package: str, old_version: str, new_version: str, summary: str) -> str:
    """Compose the markdown body for a PR comment."""
    return (
        f"## 🔍 depwatch: `{package}` {old_version} → {new_version}\n\n"
        f"{summary}\n\n"
        "<sub>Generated by [depwatch](https://github.com/depwatch/depwatch)</sub>"
    )


def post_pr_comment(repo: str, pr_number: int, body: str) -> dict:
    """
    Post a comment on a GitHub pull request.

    :param repo: Full repo name, e.g. "owner/repo"
    :param pr_number: Pull request number
    :param body: Markdown comment body
    :return: Response JSON from GitHub API
    """
    token = get_github_token()
    url = f"{GITHUB_API_BASE}/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    response = requests.post(url, json={"body": body}, headers=headers, timeout=15)
    response.raise_for_status()
    return response.json()
